# Generated by Django 4.1.5 on 2023-01-16 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_type', models.CharField(choices=[('OFF', 'Off Budget'), ('ON', 'On Budget')], default='ON', max_length=20)),
                ('commitments', models.CharField(max_length=150)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('project_status', models.CharField(choices=[('O', 'On-Going'), ('C', 'Completed')], default='O', max_length=20)),
                ('donor', models.CharField(max_length=100)),
                ('executing_agency', models.CharField(max_length=100)),
                ('implementing_partner', models.CharField(max_length=100)),
                ('counterpart_agency', models.CharField(max_length=100)),
                ('humanitarian', models.BooleanField(default=False)),
                ('assistance_code', models.IntegerField()),
                ('agremeent_date', models.DateField()),
                ('effective_date', models.DateField()),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('sector_code', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
            options={
                'unique_together': {('project_title', 'effective_date')},
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('municipality', models.CharField(max_length=100)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.budget')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.project')),
            ],
            options={
                'unique_together': {('province', 'district', 'municipality', 'project', 'budget')},
            },
        ),
    ]
